# Generated by Django 4.2.1 on 2023-05-15 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_managers_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("38358207-4ae4-47b5-9648-1886656a1ef2"), unique=True
            ),
        ),
    ]
