# Generated by Django 4.2.1 on 2023-05-15 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("67697790-25fe-4121-bf99-da38ef15bc17"), unique=True
            ),
        ),
    ]
