# Generated by Django 4.2.1 on 2023-05-15 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("5e21f677-2427-4880-bd78-d474777ed47e"), unique=True
            ),
        ),
    ]
