# Generated by Django 4.2.1 on 2023-05-16 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("67ff49f5-8780-45bb-b73e-39b8cd01ab71"), unique=True
            ),
        ),
    ]
