# Generated by Django 4.2.1 on 2023-05-16 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_product_slug_tags_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("0197fa09-5b4d-4c97-97c3-13b1eb784442"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="slug",
            field=models.SlugField(default="code", unique=True),
            preserve_default=False,
        ),
    ]
